#include QMK_KEYBOARD_H

#define _BASE 0
#define _FKEYS 1
#define _NUM 2
#define _ARROW 3
#define _UMLAUT 4

#define FN2_GRV LT(_FN2, KC_GRV)

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
  [_BASE] = LAYOUT_68_ansi(
 KC_ESC, KC_1, KC_2, KC_3, KC_4, KC_5,               KC_H, LT(4, KC_SPC), KC_NO, KC_TAB, KC_Q, KC_W, 
 KC_F, KC_P, KC_G, MO(1), MO(2), KC_NO,           KC_LSFT, KC_A, KC_R, KC_S, KC_T, KC_D, 
 KC_LALT, KC_LCTL, KC_NO, KC_Z, KC_X, KC_C,          KC_V, KC_B, KC_J, KC_NO, KC_SPC, KC_LGUI,
 KC_M, KC_BSPC, KC_NO, KC_DOT, KC_SLSH, KC_NO,       KC_NO, MO(3), KC_K, KC_7, KC_8, KC_9, 
 KC_0, KC_MINS, KC_NO, KC_COMM, KC_NO, KC_6,         KC_L, KC_U, KC_Y, KC_RBRC, KC_BSLS, KC_NO, 
 KC_LEFT, KC_NO, KC_N, KC_N, KC_E, KC_I,             KC_O, KC_RSFT
 ),

  [_FKEYS] = LAYOUT_68_ansi(
 KC_GRV, KC_F1, KC_F2, KC_F3, KC_F4, KC_F5,                    KC_F6, KC_F7, KC_F8, KC_F9, KC_F10, KC_F11,
 KC_F12, KC_PSCR, KC_TRNS, KC_TRNS, KC_DEL, KC_TRNS,           KC_TRNS, KC_QUOT, KC_TRNS, KC_MINS, KC_TRNS, KC_TRNS,
 KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,         KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_PGDN, KC_TRNS,
 KC_TRNS, KC_HOME, KC_END, LSFT(KC_NUBS), KC_BRID, KC_TRNS,    KC_TRNS, KC_TRNS, KC_TRNS, KC_F7, KC_F8, KC_F9,
 KC_F10, KC_F11, KC_F12, KC_NUBS, KC_MUTE, KC_F6,              KC_TRNS, KC_TRNS, KC_TRNS, KC_BRIU, KC_TRNS, KC_INS,
 KC_PGUP, KC_PENT, KC_TRNS, KC_TRNS, KC_TRNS, RALT(KC_NUBS),   KC_TRNS, KC_TRNS
  ),
  [_NUM] = LAYOUT_68_ansi(
 KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,      KC_TRNS, KC_MPLY, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
 KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,    KC_TRNS, KC_TRNS, KC_TRNS, SGUI(KC_S), KC_TRNS, KC_TRNS,
 KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,      KC_TRNS, KC_TRNS, KC_TRNS, KC_MUTE, KC_TRNS, KC_TRNS,
 KC_P0, KC_MPRV, KC_MNXT, KC_TRNS, KC_PMNS, KC_MUTE,      KC_PMNS, KC_TRNS, KC_TRNS, KC_P7, KC_P8, KC_P9,
 KC_PSLS, KC_PAST, KC_TRNS, KC_PDOT, KC_PPLS, KC_TRNS,      KC_P4, KC_P5, KC_P6, KC_PPLS, KC_TRNS, KC_TRNS,
 KC_TRNS, KC_TRNS, KC_TRNS, KC_P1, KC_P2, KC_P3,           KC_TRNS, KC_TRNS
  ),
  [_ARROW] = LAYOUT_68_ansi(
 LCG_SWP, LCG_NRM, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,      KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, RALT(KC_Q), KC_TRNS,
 KC_UP, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,      KC_TRNS, KC_TRNS, KC_LEFT, KC_DOWN, KC_RGHT, KC_TRNS,
 KC_RALT, KC_RCTL, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,      KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
 KC_TRNS, KC_WBAK, KC_WFWD, KC_LEFT, KC_DOWN, KC_TRNS,      KC_TRNS, KC_RGHT, KC_TRNS, KC_FIND, KC_CALC, KC_HELP,
 KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,      RALT(KC_L), KC_TRNS, KC_WFWD, KC_TRNS, KC_TRNS, KC_TRNS,
 KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,      KC_UP, KC_TRNS
  ),
  [_UMLAUT] = LAYOUT_68_ansi(
 KC_EQL, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,               KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
 KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,              KC_NO, KC_QUOT, KC_NO, KC_MINS, KC_NO, KC_NO,
 KC_NO, KC_NO, KC_NO, KC_NO, KC_BSPC, KC_NO,              KC_NO, KC_NO, KC_NO, KC_NO, KC_ENT, KC_NO,
 KC_NO, KC_DEL, KC_NO, LSFT(KC_NUBS), KC_VOLD, KC_NO,    KC_NO, KC_BRID, KC_NO, KC_NO, KC_NO, KC_NO,
 KC_NO, KC_NO, KC_NO, KC_NUBS, KC_NO, KC_NO,            KC_NO, KC_LBRC, KC_NO, KC_VOLU, KC_BRIU, KC_NO,
 KC_NO, KC_NO, KC_NO, KC_NO, KC_EQL, RALT(KC_NUBS),      KC_SCLN, KC_NO
  )
};
